### PR TITLE
Add postcss

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama I think the repo is ready for you to take a look. Is it supposed to be trying to deploy to netlify? I haven't set up any netlify things yet other than the empty lambda folder and header stuff.

**Comment by sherakama** [comment]
Yeah, I set up a Netlify environment for it today when I was setting up the CDN proxy one.

Builds are failing but that is to be expected.
https://app.netlify.com/sites/online-giving-preview/deploys/600207337fd90f00075c37ad

**Comment by yvonnetangsu** [comment]
> Yeah, I set up a Netlify environment for it today when I was setting up the CDN proxy one.
> 
> Builds are failing but that is to be expected.
> https://app.netlify.com/sites/online-giving-preview/deploys/600207337fd90f00075c37ad

Oh nice - thank you for setting that up :)

**Comment by yvonnetangsu** [comment]
@sherakama @katrialesser FYI this is just a fake PR to test things out, but we do need to add TW and postcss so it's not completely fake.

**Comment by sherakama** [comment]
I'm not sure we NEED tailwind in this repo. We are going to use it to create Decanter V7 but let's chat about whether we need it in this repo.

Also, please add postcss configuration file and the package-lock.json updates in the PR.

**Comment by yvonnetangsu** [comment]
> I'm not sure we NEED tailwind in this repo. We are going to use it to create Decanter V7 but let's chat about whether we need it in this repo.
> 
> Also, please add postcss configuration file and the package-lock.json updates in the PR.

Not directly related to your comment, but - 

I do wonder what we'll do with optimizing the output CSS file. I was thinking that we could install purgeCSS by itself, but then it won't work with the way we render class names depending on variable values passed from storyblok. We could have a common v7 CSS Decanter based file for all our projects that's cache, but that's still a huge file.

**Comment by yvonnetangsu** [comment]
> I'm not sure we NEED tailwind in this repo. We are going to use it to create Decanter V7 but let's chat about whether we need it in this repo.
> 
> Also, please add postcss configuration file and the package-lock.json updates in the PR.

@sherakama added postcss config and autoprefixer; removed TW for now. We probably need to go back to the postcss config content itself later and decide what to put there.

**Comment by sherakama** [comment]
> I do wonder what we'll do with optimizing the output CSS file. I was thinking that we could install purgeCSS by itself, but then it won't work with the way we render class names depending on variable values passed from storyblok. We could have a common v7 CSS Decanter based file for all our projects that's cache, but that's still a huge file.

Aye, you hit the nail on the head with this comment. PurgeCSS would be a very good reason to add tailwind to this project and render out our own slim version of the utility classes. I am game if you are game to give it a go. For simplicity, I was leaning towards just including the behemoth css file and moving along.

**Comment by yvonnetangsu** [comment]
> > I do wonder what we'll do with optimizing the output CSS file. I was thinking that we could install purgeCSS by itself, but then it won't work with the way we render class names depending on variable values passed from storyblok. We could have a common v7 CSS Decanter based file for all our projects that's cache, but that's still a huge file.
> 
> Aye, you hit the nail on the head with this comment. PurgeCSS would be a very good reason to add tailwind to this project and render out our own slim version of the utility classes. I am game if you are game to give it a go. For simplicity, I was leaning towards just including the behemoth css file and moving along.

I was wondering if we can install purgeCSS on its own outside of Tailwind - https://www.npmjs.com/package/purgecss
Haven't tested it, but maybe we could give it a try. I kind of feel like we do want to make use of the generic CSS file generated from Decanter v7, since configuring TW in our own project again seems a little repetitive (want to make sure of Decanter as much as possible), but I also very much dislike the idea of a 3MB CSS file even though maybe we can cache it loading it from a CDN or something 😂  So if we could just use that common gigantic CSS but able to purge it in our own repo, that'd be ideal. 

I think we'll also have to think about how to deal with the dynamic class names since we can't purge classes unless they the whole class names are fully written out in our files. So we might have to list out all the color class names for a card for example, instead of just leaving the variable name there. This article has some interesting info:
https://www.viget.com/articles/a-better-approach-for-using-purgecss-with-tailwind/

**Comment by sherakama** [comment]
I like that idea. Let's roll with purgecss in this repo and not include tw here.

**Comment by yvonnetangsu** [comment]
@katrialesser There's some discussion about TW/purgeCSS here.

**Review by katrialesser — APPROVED** [review]

**Comment by katrialesser** [comment]
> @katrialesser There's some discussion about TW/purgeCSS here.

Thanks for the mention, great conversation here. Agreed about not including and configuring tailwind again here, I would love to hear how it goes adding purgecss in this repo. I also wasn't thinking beyond including the big file haha. :)

**Comment by yvonnetangsu** [comment]
I resolved conflict and merging this into main. We can keep tweaking.

**Pull request merged**
