### PR TITLE
Integration with Decanter React Help

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Get package to build.

### CODE REVIEW

**Comment by sherakama** [comment]
With this PR. `gatsby develop` works but `npm run build` does not.

**Comment by sherakama** [comment]
One of our dependencies is putting a `window` in the output. Going to dig into this more.

**Comment by yvonnetangsu** [comment]
> One of our dependencies is putting a `window` in the output. Going to dig into this more.

Thank you for your help on this! Hope you get some rest this upcoming long weekend.

**Comment by yvonnetangsu** [comment]
Interesting, this works in develop mode 🎉 , but looks like all the TW class names with a `:` in it - all the responsive classes, :hover etc are not working 🤔  Don't think it's related to this PR though.

Screen Shot 2021-02-18 at 11 53 51 AM

**Comment by yvonnetangsu** [comment]
> Interesting, this works in develop mode 🎉 , but looks like all the TW class names with a `:` in it - all the responsive classes, :hover etc are not working 🤔 Don't think it's related to this PR though.
> 
> Screen Shot 2021-02-18 at 11 53 51 AM

This has been solved - I just need to configure my purgeCSS to accept TW class characters.

**Review by yvonnetangsu — APPROVED** [review]
I'm pre-approving since it makes `npm run develop` work! Feel free to merge when you're ready.

**Pull request merged**
